### ISSUE TITLE
PowerVS single instance "Lifecycle" view incorrectly shows "Migrate selected instances"

### ISSUE THREAD

**Issue by jwcroppe** [ManageIQ/manageiq-providers-ibm_cloud#228]
As shown in the image below, migration is incorrectly shown as a viable lifecycle operation from the single instance view.  We should cleanse this list of operations so that only supported operations for PowerVS are shown.

![image](https://user-images.githubusercontent.com/13011041/123029111-37417280-d3a6-11eb-9760-4559c1d9d318.png)

**Comment by jwcroppe** [comment]
@miq_bot add_label bug

**Comment by jwcroppe** [comment]
@jaywcarman FYI

**Comment by jwcroppe** [comment]
@miq-bot add_label bug

**Comment by agrare** [comment]
This appears to be another instance of `supports :migrate` being enabled at the base class for `Vms`

**Comment by agrare** [comment]
I just noticed this is on the list view not the instance details page.  Since there is no guarantee that the items in the list will be consistent in type the UI does not check for supported features when building the dropdowns.  The performance of checking possibly thousands of records one-by-one for each feature is impractical.

I thought we had an issue open against the UI tracking this but am unable to find it, @Fryguy do you remember?

**Comment by chessbyte** [comment]
https://github.com/ManageIQ/manageiq-ui-classic/issues/7636

**Comment by agrare** [comment]
:+1: thanks @chessbyte 

Going to close this as a "known issue" now and continue discussion over at https://github.com/ManageIQ/manageiq-ui-classic/issues/7636
